<a href="https://colab.research.google.com/github/Momegaii/Momegaii/blob/main/np_for_nns.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Understanding NumPy Arrays & Shapes

NumPy Arrays & Shapes – The Foundations

In [2]:
import numpy as np

In [3]:
scaler = np.array(5)
print(scaler)
print(scaler.shape)
print(scaler.ndim)

5
()
0


In [4]:
vector = np.array([1,2,3])
print(vector)
print(vector.shape)
print(vector.ndim)

[1 2 3]
(3,)
1


In [5]:
matrix= np.array([[1,2],[4,5]])
print(matrix)
print(matrix.shape)
print(matrix.ndim)


[[1 2]
 [4 5]]
(2, 2)
2


this is the most important in nns bcs it deals with mor than 2 dems

In [6]:
tensor3d = np.array([[[1,2],[3,4]], [[5,6],[7,8]]])
print(tensor3d)
print(tensor3d.shape)
print(tensor3d.ndim)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
(2, 2, 2)
3


Inspect Properties

In [7]:
a = np.array([[1,2,3],[3,4,5]])


print(a)
print(a.shape)
print(a.dtype)
print(a.ndim)


[[1 2 3]
 [3 4 5]]
(2, 3)
int64
2


In [8]:
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

print('shape:',arr.shape)
print("whole :",arr)
print("deminsions:",arr.ndim)

shape: (3, 4)
whole : [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
deminsions: 2


# Reshaping & Flattening

In [ ]:
arr = np.array([[1,2,3,4],
               [5,6,7,8],
               [9,10,11,12]])

reshape = arr.reshape(4,3)
print(reshape)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


this right here for making the arrays flat have no shape

In [ ]:
flat1 = arr.flatten()
flat2 = arr.ravel()
print(flat1)
print(flat2)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [ ]:
a = np.array([[[5]]])

asqueezed = np.squeeze(a)

print(a.shape)
print(asqueezed)

(1, 1, 1)
5


In [ ]:
vec = np.array([1,2,3])

print(vec.shape)

new_vec = np.expand_dims(vec, axis=0)

print(new_vec)

new_vec2  = np.expand_dims(vec, axis= 1)

print(new_vec2)

(3,)
[[1 2 3]]
[[1]
 [2]
 [3]]


In [ ]:
arr = np.array([[1,2,3],[4,5,6]])

print("\n arr :\n",arr)
print(" ")
shape = arr.shape

print("s: ",shape)
print(" ")
reshape = arr.reshape(3,2)

print("rs:",reshape)
print(" ")
flt = arr.flatten()
print(" ")
print("flt:",flt)
print(" ")
exp = np.expand_dims(arr, axis=0)
print(" ")
print("ex[:]",exp)

sqz = arr.squeeze()
print("sqee: ",sqz)
print(" ")


 arr :
 [[1 2 3]
 [4 5 6]]
 
s:  (2, 3)
 
rs: [[1 2]
 [3 4]
 [5 6]]
 
 
flt: [1 2 3 4 5 6]
 
 
ex[:] [[[1 2 3]
  [4 5 6]]]
sqee:  [[1 2 3]
 [4 5 6]]
 


# Broadcasting

In [10]:
a = np.array([1,2,3])
b = np.array([[10],[20],[30]])


res = a+b

print(res)

[[11 12 13]
 [21 22 23]
 [31 32 33]]


What happened?
a (1D) got broadcast to shape (3,3) to match b

NumPy automatically matched dimensions

In [12]:
arr = np.array([1,2,3])

reshaped = arr[:, np.newaxis]
print(reshaped)

[[1]
 [2]
 [3]]


In [13]:
a = np.array([1, 2, 3])
b = np.array([[10], [20], [30]])

print("a shape:", a.shape)
print("b shape:", b.shape)

c = a + b
print("Result:\n", c)
print("Result shape:", c.shape)


a shape: (3,)
b shape: (3, 1)
Result:
 [[11 12 13]
 [21 22 23]
 [31 32 33]]
Result shape: (3, 3)


# Matrix Multiplication

In [31]:
arr = np.array([[1,2,3],[4,5,6]])


arr[1,0]

arr[:,0]

arr[1,:]

arr[0]

np.sum(arr)
np.sum(arr, axis=0)
np.sum(arr, axis=1)

array([ 6, 15])

#  Debugging Shape Errors

In [32]:
arr = np.array([[1,2,3],
                [4,5,6]])

print(arr[0,1])
print(arr[:,2])
print(arr.sum(axis=1))

2
[3 6]
[ 6 15]


# NN and numpy

Matrix Multiplication in Neural Nets

In [ ]:
#The core equation of a neuron is

z = w @ x +  b

In [35]:
x = np.array([0.5,1.5])
w = np.array([[0.1,0.2],[0.3,0.4],[0.5,0.6]])
b = np.array([0.1,0.2,0.3])

z = w @ x + b

Activation Functions

In [38]:
print(z)
def sigmoid(z):
  return 1 / (1+np.exp(-z))

sigmoid(z)

[0.45 0.95 1.45]


array([0.61063923, 0.72111518, 0.80999843])

in sigmoid we use np.exp(-x)

to turn any number into posibillty

even the the negative bcs signmoid is for yes or no methods binary

exrc

In [39]:
x = np.random.randn(21)
print(x)

[ 0.08465418  2.05703054  0.01891067 -1.0554803   1.4163789   0.33080975
  1.49145661 -0.23527365 -0.37282436 -1.03138406 -1.02457038  2.30060313
  0.41444902 -1.35990669  0.66455408  1.32476348  0.81687523  0.3801228
 -1.27123204 -0.03992034  0.19458337]


In [41]:
w = np.random.randn(10,21)
print(w)

[[ 0.77942405 -0.5447664   0.22717355  0.59409383 -0.63777292 -0.20019552
   0.75664951 -1.11608268 -1.39571942  1.12954401  0.79193163 -0.19018581
   1.56078382 -0.34804056 -0.51947654  0.34361758  0.68716275 -0.60147962
   0.34530706 -1.83135804  1.75205065]
 [ 0.99750652  0.41905928  0.70815175 -1.29644138 -0.65811661  0.40324834
  -0.78136429 -0.16314317 -0.35838353  0.92419131  0.41738494 -0.15944369
  -1.08887915  0.64338205  1.18258801  0.48246594  0.01632081 -0.26584932
  -0.24767928 -1.86249908 -0.9473074 ]
 [-0.47829439  0.00460648 -0.18498544  1.39270217  0.79073886  0.72505422
  -0.02190661  0.21582472  0.81035567 -0.17452939  1.79122501 -0.92171868
   0.88993964 -1.54791818  1.55267188  2.05724112  1.66350267 -1.38364658
   1.74141077  0.72708626  1.89934343]
 [ 1.44364385  0.70731877  1.14642054  0.2268795   0.67192377 -0.71723145
   0.78082798  0.34902845  1.43087467 -0.68856788  0.04749105 -0.45533983
  -0.831893    1.03428735  1.08013452  2.09531004  1.29605352  0.2850

In [42]:
b = np.random.randn(10)

print(b)

[ 1.26334059 -0.06073314 -1.79899862 -0.49930235  0.31338484 -1.5827529
 -0.05218075 -0.7148157  -0.10763471 -1.2500275 ]


In [44]:
z = w @ x + b

print(z)

[-0.34815175 -1.05630465 -0.91416101  4.34256814  1.7552293  11.32624167
  1.66556194  3.5592563  -3.40131204 -1.60398992]
